python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/7z/fffiletype .7z
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/avi/fffiletype .avi
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/bmp/fffiletype .bmp
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/bnp/fffiletype .bnp
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/bz2/fffiletype .bz2
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/cbr/fffiletype .cbr
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/cbz/fffiletype .cbz 
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/epub/fffiletype .epub
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/exe/fffiletype .exe
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/fl/fffiletype .fl
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/flac/fffiletype .flac
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/flv/fffiletype .flv
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/gif/fffiletype .gif
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/gz/fffiletype .gz
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/inp/fffiletype .inp
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/iso/fffiletype .iso
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/jpg/fffiletype .jpg
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4a/fffiletype .m4a
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4b/fffiletype .m4b
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4p/fffiletype .m4p
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mkv/fffiletype .mkv
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mov/fffiletype .mov
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mp3/fffiletype .mp3
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mp4/fffiletype .mp4
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mpeg/fffiletype .mpeg
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/mpg/fffiletype .mpg
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/msi/fffiletype .msi
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/pdf/fffiletype .pdf
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/png/fffiletype .png
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/rar/fffiletype .rar
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/rm/fffiletype .rm
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/tar/fffiletype .tar
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/tgz/fffiletype .tgz
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/tif/fffiletype .tif
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/txt/fffiletype .txt
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/vob/fffiletype .vob
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/w4v/fffiletype .w4v
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/wav/fffiletype .wav
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/wma/fffiletype .wma
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/wmv/fffiletype .wmv
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/zip/fffiletype .zip
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4v/fffiletype .m4v
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4v/fffiletype .m4v
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/arw/fffiletype .arw
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/xcf/fffiletype .xcf
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/raw/fffiletype .raw
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/m4v/fffiletype .m4v
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/arw/fffiletype .arw
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/xcf/fffiletype .xcf
python3.6 filetreetui.py -m /media/joshua/Data11/media /media/joshua/Data11/media /media/joshua/Data11/media_type/raw/fffiletype .raw
